[disk]
product = "Gilgamesh Sorcerian"
name = "Disk 2"
sha1 = "511709f2ab4f0887aca815737dc9644188e365a9"

[[entry]]
filename = "MENU"
type = "menu"

[[entry]]
filename = "TR030"
type = "treasure"
[[entry]]
filename = "TR040"
type = "treasure"

[[entry]]
filename = "NC030"
type = "image"
format = "sprite"
patterns = { filename = "NP030", offset = 0x90, base = 0x60, count = 8, mode = "2x3" }
size = [32, 128]
tile_size = [16, 8]
[[entry]]
filename = "NC040"
type = "image"
format = "sprite"
# patterns = { filename = "NP040", offset = 0x90, base = 0x60, count = 8, mode = "2x3" }
size = [32, 128]
tile_size = [16, 8]
