[disk]
product = "Selected Sorcerian 2"
name = "Disk 1"
sha1 = "b897d5321cff066c12c0769e4c722fc0d04c1eeb"

[[entry]]
filename = "MENU"
type = "menu"

[[entry]]
filename = "TR020"
type = "treasure"
[[entry]]
filename = "TR030"
type = "treasure"
