[disk]
product = "Selected Sorcerian 4"
name = "Disk 1"
sha1 = "93bef5ef412af1c9c2269f28a885ef7a7a8fd8d3"

[[entry]]
filename = "MENU"
type = "menu"

[[entry]]
filename = "TR050"
type = "treasure"
[[entry]]
filename = "TR070"
type = "treasure"
