[disk]
product = "Selected Sorcerian 3"
name = "Disk 1"
sha1 = "80d1fd3f74cd57f50f0ed3e82257bcbb43dbab5f"

[[entry]]
filename = "MENU"
type = "menu"

[[entry]]
filename = "TR060"
type = "treasure"
[[entry]]
filename = "TR090"
type = "treasure"

[[entry]]
filename = "NC060"
type = "image"
format = "sprite"
patterns = { filename = "NP060", offset = 0x90, base = 0x60, count = 8, mode = "2x3" }
size = [32, 128]
tile_size = [16, 8]
[[entry]]
filename = "NC090"
type = "image"
format = "sprite"
patterns = { filename = "NP090", offset = 0x90, base = 0x60, count = 8, mode = "2x3" }
size = [32, 128]
tile_size = [16, 8]
