[disk]
product = "Selected Sorcerian 1"
name = "Disk 1"
sha1 = "fb4ac16f1978143ab05a6df84fca0558ba504b89"

[[entry]]
filename = "MENU"
type = "menu"

[[entry]]
filename = "TR010"
type = "treasure"
[[entry]]
filename = "TR020"
type = "treasure"

[[entry]]
filename = "NC010"
type = "image"
format = "sprite"
patterns = { filename = "NP010", offset = 0x90, base = 0x60, count = 8, mode = "2x3" }
size = [32, 128]
tile_size = [16, 8]
[[entry]]
filename = "NC020"
type = "image"
format = "sprite"
patterns = { filename = "NP020", offset = 0x90, base = 0x60, count = 8, mode = "2x3" }
size = [32, 128]
tile_size = [16, 8]
