[disk]
product = "Selected Sorcerian 2"
name = "Disk 1"
sha1 = "b897d5321cff066c12c0769e4c722fc0d04c1eeb"

[[entry]]
filename = "MENU"
type = "menu"

[[entry]]
filename = "TR020"
type = "treasure"
[[entry]]
filename = "TR030"
type = "treasure"

[[entry]]
filename = "NC020"
type = "image"
format = "sprite"
patterns = { filename = "NP020", offset = 0x90, base = 0x60, count = 8, mode = "2x3" }
size = [32, 128]
tile_size = [16, 8]
[[entry]]
filename = "NC030"
type = "image"
format = "sprite"
patterns = { filename = "NP030", offset = 0x90, base = 0x60, count = 8, mode = "2x3" }
size = [32, 128]
tile_size = [16, 8]
