[disk]
product = "Sorcerian"
name = "Scenario 2"
sha1 = "7fdb449f8b11a07a6588e8b5db3fdcf840c2eeb3"

[[entry]]
filename = "MENU"
type = "menu"

[[entry]]
filename = "TR100"
type = "treasure"
[[entry]]
filename = "TR110"
type = "treasure"
[[entry]]
filename = "TR120"
type = "treasure"
[[entry]]
filename = "TR130"
type = "treasure"
[[entry]]
filename = "TR140"
type = "treasure"

[[entry]]
filename = "NC110"
type = "image"
format = "sprite"
patterns = { filename = "NP110", offset = 0x90, base = 0x60, count = 8, mode = "2x3" }
size = [32, 128]
tile_size = [16, 8]
[[entry]]
filename = "NC130"
type = "image"
format = "sprite"
patterns = { filename = "NP130", offset = 0x90, base = 0x60, count = 8, mode = "2x3" }
size = [32, 128]
tile_size = [16, 8]
[[entry]]
filename = "NC140"
type = "image"
format = "sprite"
patterns = { filename = "NP140", offset = 0x90, base = 0x60, count = 8, mode = "2x3" }
size = [32, 128]
tile_size = [16, 8]
