[disk]
product = "Sorcerian"
name = "Main Disk v1.1"
sha1 = "93ae153e2976835ad8232a4c1492ba2e84bc7625"

[listing]
type = "dir"
start = [1, 1]
size = 0x4b0

[[entry]]
filename = "      "
type = "code"
write_as = "KERNEL.bin"

[[entry]]
filename = "MOGI1"
type = "image"
format = "planar"
size = [640, 152]
[[entry]]
filename = "MOGI2"
type = "image"
format = "planar"
size = [640, 152]
[[entry]]
filename = "TAIT1"
type = "image"
format = "planar"
size = [640, 152]
[[entry]]
filename = "TAIT2"
type = "image"
format = "planar"
size = [640, 152]

[[entry]]
filename = "PRNO0"
type = "code"
[[entry]]
filename = "PRNO1"
type = "code"
[[entry]]
filename = "PRNO2"
type = "code"
[[entry]]
filename = "PRNO3"
type = "code"
[[entry]]
filename = "PRNO4"
type = "code"
[[entry]]
filename = "PRNO6"
type = "code"
[[entry]]
filename = "PRNO7"
type = "code"

[[entry]]
filename = "TEXT"
type = "image"
format = "1bpp"
size = [256, 128]
tile_size = [16, 8]
