[disk]
product = "Sorcerian"
name = "Scenario 3"
sha1 = "3e696964ce55876d0456c94d5b10b9af4777bad6"

[[entry]]
filename = "MENU"
type = "menu"

[[entry]]
filename = "TR200"
type = "treasure"
[[entry]]
filename = "TR210"
type = "treasure"
[[entry]]
filename = "TR220"
type = "treasure"
[[entry]]
filename = "TR230"
type = "treasure"
[[entry]]
filename = "TR240"
type = "treasure"

[[entry]]
filename = "NC200"
type = "image"
format = "sprite"
patterns = { filename = "NP200", offset = 0x90, base = 0x60, count = 8, mode = "2x3" }
size = [32, 128]
tile_size = [16, 8]
[[entry]]
filename = "NC220"
type = "image"
format = "sprite"
patterns = { filename = "NP220", offset = 0x90, base = 0x60, count = 8, mode = "2x3" }
size = [32, 128]
tile_size = [16, 8]
