[disk]
product = "Sorcerian"
name = "Scenario 1"
sha1 = "2abcfcda58b5d5390be5371a4b545fc233c019ff"

[[entry]]
filename = "C_000"
type = "image"
format = "sprite"
size = [128, 128]
tile_size = [16, 8]
[[entry]]
filename = "C_001"
type = "image"
format = "sprite"
patterns = { filename = "P_001", base = 0xa0, mode = "multi" }
size = [96, 128]
tile_size = [16, 8]
mount = 0xe800
[[entry]]
filename = "C_003"
type = "image"
format = "sprite"
patterns = { filename = "P_003", base = 0xa0, mode = "multi" }
size = [96, 128]
tile_size = [16, 8]
mount = 0xe800
[[entry]]
filename = "C_010"
type = "image"
format = "sprite"
size = [128, 128]
tile_size = [16, 8]
[[entry]]
filename = "C_011"
type = "image"
format = "sprite"
patterns = { filename = "P_011", base = 0xa0, mode = "multi" }
size = [96, 128]
tile_size = [16, 8]
mount = 0xe800
[[entry]]
filename = "C_013"
type = "image"
format = "sprite"
patterns = { filename = "P_013", base = 0xa0, mode = "multi" }
size = [96, 128]
tile_size = [16, 8]
mount = 0xe800
[[entry]]
filename = "C_020"
type = "image"
format = "sprite"
size = [128, 128]
tile_size = [16, 8]
[[entry]]
filename = "C_021"
type = "image"
format = "sprite"
patterns = { filename = "P_021", base = 0xa0, mode = "multi" }
size = [96, 128]
tile_size = [16, 8]
mount = 0xe800
[[entry]]
filename = "C_023"
type = "image"
format = "sprite"
patterns = { filename = "P_023", base = 0xa0, mode = "multi" }
size = [96, 128]
tile_size = [16, 8]
mount = 0xe800
[[entry]]
filename = "C_030"
type = "image"
format = "sprite"
size = [128, 128]
tile_size = [16, 8]
[[entry]]
filename = "C_031"
type = "image"
format = "sprite"
patterns = { filename = "P_031", base = 0xa0, mode = "multi" }
size = [96, 128]
tile_size = [16, 8]
mount = 0xe800
[[entry]]
filename = "C_033"
type = "image"
format = "sprite"
patterns = { filename = "P_033", base = 0xa0, mode = "multi" }
size = [96, 128]
tile_size = [16, 8]
mount = 0xe800
[[entry]]
filename = "C_040"
type = "image"
format = "sprite"
size = [128, 128]
tile_size = [16, 8]
[[entry]]
filename = "C_041"
type = "image"
format = "sprite"
patterns = { filename = "P_041", base = 0xa0, mode = "multi" }
size = [96, 128]
tile_size = [16, 8]
mount = 0xe800
[[entry]]
filename = "C_043"
type = "image"
format = "sprite"
patterns = { filename = "P_043", base = 0xa0, mode = "multi" }
size = [96, 128]
tile_size = [16, 8]
mount = 0xe800

[[entry]]
filename = "MA000"
[[entry]]
filename = "MA001"
[[entry]]
filename = "MA010"
[[entry]]
filename = "MA011"
[[entry]]
filename = "MA020"
[[entry]]
filename = "MA021"
[[entry]]
filename = "MA030"
[[entry]]
filename = "MA031"
[[entry]]
filename = "MA040"
[[entry]]
filename = "MA041"

[[entry]]
filename = "MENU"
type = "menu"

[[entry]]
filename = "MENUZZ"
type = "text"
encoding = "shift-jis"

[[entry]]
filename = "M_000"
[[entry]]
filename = "M_001"
[[entry]]
filename = "M_002"
[[entry]]
filename = "M_003"
[[entry]]
filename = "M_004"
[[entry]]
filename = "M_005"
[[entry]]
filename = "M_006"
[[entry]]
filename = "M_010"
[[entry]]
filename = "M_011"
[[entry]]
filename = "M_012"
[[entry]]
filename = "M_013"
[[entry]]
filename = "M_014"
[[entry]]
filename = "M_015"
[[entry]]
filename = "M_016"
[[entry]]
filename = "M_017"
[[entry]]
filename = "M_020"
[[entry]]
filename = "M_021"
[[entry]]
filename = "M_022"
[[entry]]
filename = "M_023"
[[entry]]
filename = "M_024"
[[entry]]
filename = "M_025"
[[entry]]
filename = "M_030"
[[entry]]
filename = "M_031"
[[entry]]
filename = "M_032"
[[entry]]
filename = "M_033"
[[entry]]
filename = "M_034"
[[entry]]
filename = "M_035"
[[entry]]
filename = "M_036"
[[entry]]
filename = "M_040"
[[entry]]
filename = "M_041"
[[entry]]
filename = "M_042"
[[entry]]
filename = "M_043"
[[entry]]
filename = "M_044"
[[entry]]
filename = "M_045"
[[entry]]
filename = "M_046"
[[entry]]
filename = "M_047"
[[entry]]
filename = "M_048"
[[entry]]
filename = "M_049"
[[entry]]
filename = "M_250"
mount = 0x5800
[[entry]]
filename = "M_251"
mount = 0x5800

[[entry]]
filename = "SS001"
[[entry]]
filename = "SS005"
[[entry]]
filename = "SS006"
[[entry]]
filename = "SS010"
[[entry]]
filename = "SS011"
[[entry]]
filename = "SS016"
[[entry]]
filename = "SS017"
[[entry]]
filename = "SS026"
[[entry]]
filename = "SS027"
[[entry]]
filename = "SS029"
[[entry]]
filename = "SS037"
[[entry]]
filename = "SS041"
[[entry]]
filename = "SS049"
[[entry]]
filename = "SS054"
[[entry]]
filename = "SS055"
[[entry]]
filename = "SS058"
[[entry]]
filename = "SS060"
[[entry]]
filename = "SS081"
[[entry]]
filename = "SS082"
[[entry]]
filename = "SS085"
[[entry]]
filename = "SS087"
[[entry]]
filename = "SS088"
[[entry]]
filename = "SS090"
[[entry]]
filename = "SS099"

[[entry]]
filename = "S_000"
type = "scenario"
mount = 0x7600
[[entry]]
filename = "S_001"
type = "scenario"
mount = 0x7600
[[entry]]
filename = "S_010"
type = "scenario"
mount = 0x7600
[[entry]]
filename = "S_011"
type = "scenario"
mount = 0x7600
[[entry]]
filename = "S_020"
type = "scenario"
mount = 0x7600
[[entry]]
filename = "S_021"
type = "scenario"
mount = 0x7600
[[entry]]
filename = "S_030"
type = "scenario"
mount = 0x7600
[[entry]]
filename = "S_031"
type = "scenario"
mount = 0x7600
[[entry]]
filename = "S_040"
type = "scenario"
mount = 0x7600
[[entry]]
filename = "S_041"
type = "scenario"
mount = 0x7600
[[entry]]
filename = "S_042"
type = "scenario"
mount = 0x7600
[[entry]]
filename = "S_043"
type = "scenario"
mount = 0x7600
[[entry]]
filename = "S_044"
type = "scenario"
mount = 0x7600

[[entry]]
filename = "TR000"
type = "treasure"
[[entry]]
filename = "TR010"
type = "treasure"
[[entry]]
filename = "TR020"
type = "treasure"
[[entry]]
filename = "TR030"
type = "treasure"
[[entry]]
filename = "TR040"
type = "treasure"
