[disk]
product = "Sorcerian"
name = "v1.1 Main Disk"
sha1 = "93ae153e2976835ad8232a4c1492ba2e84bc7625"

[listing]
type = "dir"
start = [1, 1]
size = 0x4b0

[[entry]]
filename = "TEXT"
type = "image"
format = "1bpp"
width = 256
height = 128
tile_width = 16
tile_height = 8
