[disk]
product = "Sorcerian"
name = "Main Disk v1.1"
sha1 = "93ae153e2976835ad8232a4c1492ba2e84bc7625"

[listing]
type = "dir"
start = [1, 1]
size = 0x4b0

[[entry]]
filename = "      "
type = "code"
write_as = "KERNEL.bin"
mount = 0

[[entry]]
filename = "CH000"
type = "image"
format = "sprite"
patterns = { filename = "PLPTR", offset = 0x000, count = 8, mode = "2x3" }
size = [32, 128]
tile_size = [16, 8]
mount = 0x5400
[[entry]]
filename = "CH001"
type = "image"
format = "sprite"
patterns = { filename = "PLPTR", offset = 0x040, count = 8, mode = "2x3" }
size = [32, 128]
tile_size = [16, 8]
mount = 0x5400
[[entry]]
filename = "CH002"
type = "image"
format = "sprite"
patterns = { filename = "PLPTR", offset = 0x080, count = 8, mode = "2x3" }
size = [32, 128]
tile_size = [16, 8]
mount = 0x5400
[[entry]]
filename = "CH010"
type = "image"
format = "sprite"
patterns = { filename = "PLPTR", offset = 0x100, count = 8, mode = "2x3" }
size = [32, 128]
tile_size = [16, 8]
mount = 0x5400
[[entry]]
filename = "CH011"
type = "image"
format = "sprite"
patterns = { filename = "PLPTR", offset = 0x140, count = 8, mode = "2x3" }
size = [32, 128]
tile_size = [16, 8]
mount = 0x5400
[[entry]]
filename = "CH012"
type = "image"
format = "sprite"
patterns = { filename = "PLPTR", offset = 0x180, count = 8, mode = "2x3" }
size = [32, 128]
tile_size = [16, 8]
mount = 0x5400
[[entry]]
filename = "CH100"
type = "image"
format = "sprite"
patterns = { filename = "PLPTR", offset = 0x200, count = 8, mode = "2x3" }
size = [32, 128]
tile_size = [16, 8]
mount = 0x5400
[[entry]]
filename = "CH101"
type = "image"
format = "sprite"
patterns = { filename = "PLPTR", offset = 0x240, count = 8, mode = "2x3" }
size = [32, 128]
tile_size = [16, 8]
mount = 0x5400
[[entry]]
filename = "CH102"
type = "image"
format = "sprite"
patterns = { filename = "PLPTR", offset = 0x280, count = 8, mode = "2x3" }
size = [32, 128]
tile_size = [16, 8]
mount = 0x5400
[[entry]]
filename = "CH110"
type = "image"
format = "sprite"
patterns = { filename = "PLPTR", offset = 0x300, count = 8, mode = "2x3" }
size = [32, 128]
tile_size = [16, 8]
mount = 0x5400
[[entry]]
filename = "CH111"
type = "image"
format = "sprite"
patterns = { filename = "PLPTR", offset = 0x340, count = 8, mode = "2x3" }
size = [32, 128]
tile_size = [16, 8]
mount = 0x5400
[[entry]]
filename = "CH112"
type = "image"
format = "sprite"
patterns = { filename = "PLPTR", offset = 0x380, count = 8, mode = "2x3" }
size = [32, 128]
tile_size = [16, 8]
mount = 0x5400
[[entry]]
filename = "CH200"
type = "image"
format = "sprite"
patterns = { filename = "PLPTR", offset = 0x400, count = 8, mode = "2x3" }
size = [32, 128]
tile_size = [16, 8]
mount = 0x5400
[[entry]]
filename = "CH201"
type = "image"
format = "sprite"
patterns = { filename = "PLPTR", offset = 0x440, count = 8, mode = "2x3" }
size = [32, 128]
tile_size = [16, 8]
mount = 0x5400
[[entry]]
filename = "CH202"
type = "image"
format = "sprite"
patterns = { filename = "PLPTR", offset = 0x480, count = 8, mode = "2x3" }
size = [32, 128]
tile_size = [16, 8]
mount = 0x5400
[[entry]]
filename = "CH210"
type = "image"
format = "sprite"
patterns = { filename = "PLPTR", offset = 0x500, count = 8, mode = "2x3" }
size = [32, 128]
tile_size = [16, 8]
mount = 0x5400
[[entry]]
filename = "CH211"
type = "image"
format = "sprite"
patterns = { filename = "PLPTR", offset = 0x540, count = 8, mode = "2x3" }
size = [32, 128]
tile_size = [16, 8]
mount = 0x5400
[[entry]]
filename = "CH212"
type = "image"
format = "sprite"
patterns = { filename = "PLPTR", offset = 0x580, count = 8, mode = "2x3" }
size = [32, 128]
tile_size = [16, 8]
mount = 0x5400
[[entry]]
filename = "CH300"
type = "image"
format = "sprite"
patterns = { filename = "PLPTR", offset = 0x600, count = 8, mode = "2x3" }
size = [32, 128]
tile_size = [16, 8]
mount = 0x5400
[[entry]]
filename = "CH301"
type = "image"
format = "sprite"
patterns = { filename = "PLPTR", offset = 0x640, count = 8, mode = "2x3" }
size = [32, 128]
tile_size = [16, 8]
mount = 0x5400
[[entry]]
filename = "CH302"
type = "image"
format = "sprite"
patterns = { filename = "PLPTR", offset = 0x680, count = 8, mode = "2x3" }
size = [32, 128]
tile_size = [16, 8]
mount = 0x5400
[[entry]]
filename = "CH310"
type = "image"
format = "sprite"
patterns = { filename = "PLPTR", offset = 0x700, count = 8, mode = "2x3" }
size = [32, 128]
tile_size = [16, 8]
mount = 0x5400
[[entry]]
filename = "CH311"
type = "image"
format = "sprite"
patterns = { filename = "PLPTR", offset = 0x740, count = 8, mode = "2x3" }
size = [32, 128]
tile_size = [16, 8]
mount = 0x5400
[[entry]]
filename = "CH312"
type = "image"
format = "sprite"
patterns = { filename = "PLPTR", offset = 0x780, count = 8, mode = "2x3" }
size = [32, 128]
tile_size = [16, 8]
mount = 0x5400

[[entry]]
filename = "C_003"
type = "image"
format = "sprite"
patterns = { filename = "P_003", base = 0xa0, mode = "multi" }
size = [64, 192]
tile_size = [16, 8]
[[entry]]
filename = "C_013"
type = "image"
format = "sprite"
patterns = { filename = "P_013", base = 0xa0, mode = "multi" }
size = [96, 128]
tile_size = [16, 8]
[[entry]]
filename = "C_023"
type = "image"
format = "sprite"
patterns = { filename = "P_023", base = 0xa0, mode = "multi" }
size = [96, 128]
tile_size = [16, 8]
[[entry]]
filename = "C_033"
type = "image"
format = "sprite"
patterns = { filename = "P_033", base = 0xa0, mode = "multi" }
size = [96, 128]
tile_size = [16, 8]
[[entry]]
filename = "C_250"
type = "image"
format = "sprite"
size = [128, 128]
tile_size = [16, 8]
[[entry]]
filename = "C_251"
type = "image"
format = "sprite"
size = [128, 128]
tile_size = [16, 8]
[[entry]]
filename = "C_600"
type = "image"
format = "sprite"
size = [32, 128]
tile_size = [16, 8]
[[entry]]
filename = "C_990"
[[entry]]
filename = "C_991"
[[entry]]
filename = "C_992"
[[entry]]
filename = "C_999"

[[entry]]
filename = "ENDTX"

[[entry]]
filename = "MA001"
[[entry]]
filename = "MA011"
[[entry]]
filename = "MA021"
[[entry]]
filename = "MA031"

[[entry]]
filename = "MOGI1"
type = "image"
format = "planar"
size = [640, 152]
[[entry]]
filename = "MOGI2"
type = "image"
format = "planar"
size = [640, 152]

[[entry]]
filename = "M_250"
[[entry]]
filename = "M_999"

[[entry]]
filename = "PLPTR"
mount = 0xa000

[[entry]]
filename = "PRNO0"
type = "code"
mount = 0x1000
[[entry]]
filename = "PRNO1"
type = "code"
mount = 0x1000
[[entry]]
filename = "PRNO2"
type = "code"
mount = 0x1000
[[entry]]
filename = "PRNO3"
type = "code"
mount = 0x1000
[[entry]]
filename = "PRNO4"
type = "code"
mount = 0x1000
[[entry]]
filename = "PRNO6"
type = "code"
mount = 0x1000
[[entry]]
filename = "PRNO7"
type = "code"
mount = 0x1000

[[entry]]
filename = "SS005"
[[entry]]
filename = "SS011"
[[entry]]
filename = "SS018"
[[entry]]
filename = "SS020"
[[entry]]
filename = "SS026"
[[entry]]
filename = "SS040"
[[entry]]
filename = "SS043"
[[entry]]
filename = "SS061"
[[entry]]
filename = "SS062"
[[entry]]
filename = "SS091"
[[entry]]
filename = "SS098"

[[entry]]
filename = "TAIT1"
type = "image"
format = "planar"
size = [640, 152]
[[entry]]
filename = "TAIT2"
type = "image"
format = "planar"
size = [640, 152]

[[entry]]
filename = "TEXT"
type = "image"
format = "1bpp"
size = [256, 128]
tile_size = [16, 8]
