[disk]
product = "Sorcerian"
name = "Main Disk v1.0"
sha1 = "c1843613d925be2ce2811aaa1f7ecc6185f5edd9"

[listing]
type = "dir"
start = [1, 1]
size = 0x4b0

[[entry]]
filename = "TEXT"
type = "image"
format = "1bpp"
size = [256, 128]
tile_size = [16, 8]
