[disk]
product = "Sorcerian Additional Scenario Vol. 2 - Sengoku Sorcerian"
name = "Disk 2"
sha1 = "9f10910560f45d61010b68c07a82bff3d4d7770f"

[[entry]]
filename = "MENU"
type = "menu"

[[entry]]
filename = "TR130"
type = "treasure"
[[entry]]
filename = "TR140"
type = "treasure"

[[entry]]
filename = "NC130"
type = "image"
format = "sprite"
# patterns = { filename = "NP130", offset = 0x90, base = 0x60, count = 8, mode = "2x3" }
size = [32, 128]
tile_size = [16, 8]
[[entry]]
filename = "NC140"
type = "image"
format = "sprite"
patterns = { filename = "NP140", offset = 0x90, base = 0x60, count = 8, mode = "2x3" }
size = [32, 128]
tile_size = [16, 8]
