[disk]
product = "Sorcerian Additional Scenario Vol. 1"
sha1 = "d7a9df141548c0659c20ac99adf79cbc934829aa"

[[entry]]
filename = "MENU"
type = "menu"

[[entry]]
filename = "TR000"
type = "treasure"
[[entry]]
filename = "TR010"
type = "treasure"
[[entry]]
filename = "TR020"
type = "treasure"
[[entry]]
filename = "TR030"
type = "treasure"
[[entry]]
filename = "TR040"
type = "treasure"

[[entry]]
filename = "NC010"
type = "image"
format = "sprite"
patterns = { filename = "NP010", offset = 0x90, base = 0x60, count = 8, mode = "2x3" }
size = [32, 128]
tile_size = [16, 8]
[[entry]]
filename = "NC030"
type = "image"
format = "sprite"
patterns = { filename = "NP030", offset = 0x90, base = 0x60, count = 8, mode = "2x3" }
size = [32, 128]
tile_size = [16, 8]
[[entry]]
filename = "NC040"
type = "image"
format = "sprite"
patterns = { filename = "NP040", offset = 0x90, base = 0x60, count = 8, mode = "2x3" }
size = [32, 128]
tile_size = [16, 8]
